cwruRobotics/rov-24

- src/surface/gui/setup.py
- src/surface/surface_main/scripts/ROS2-Install-Humble.sh
The gui was crashing because it was missing cv2.typing. Added it to dependencies by adding opencv-python-headless.
Should eventually write script to install dependencies from setup files but, that will come later maybe.
#21 
closes #22 
#21 
- Closes #
#22
> fixed gui crash

- src/surface/surface_main/scripts/ROS2-Install-Humble.sh
> Fix pip not installing properly on WSL

- src/pi/pi_main/test/test_flake8.py
- src/pi/pi_main/test/test_pep257.py
- src/pi/realsense/test/test_flake8.py
- src/pi/realsense/test/test_pep257.py
- src/surface/ps5_controller/test/test_flake8.py
- src/surface/ps5_controller/test/test_pep257.py
- src/surface/surface_main/test/test_flake8.py
- src/surface/surface_main/test/test_pep257.py
We somehow missed these tests lol.
> add missing test files

- src/pi/pi_main/README.md
Add Documentation on enabling internet sharing on Linux.
> Add Linux internet sharing

- src/surface/gui/gui/event_nodes/client.py
- src/surface/gui/gui/widgets/arm.py
Improves readability of info messages by having proper namespace in message.
> added namespace argument to GUIEventClient

- .vscode/install_dependencies.sh
- Dockerfile
Add a PyQt dependency to the install script
- Closes #
> Add libxcb-cursor0 to install script

- src/pi/pi_main/README.md
- src/pi/pi_main/launch/pi_launch.py
- src/pi/pi_main/pi_main/ip_publisher.py
- src/pi/pi_main/pi_main/run_on_boot.py
- src/pi/pi_main/setup.py
- src/rov_msgs/CMakeLists.txt
- src/rov_msgs/msg/IPAddress.msg
- src/surface/gui/README.md
Uses some stack overflow magic to get the ip address then publishes over ROS. If our pi_main install thing is used will run on boot up.
- Closes #
#103
> Publishes IP address of PI over ROS

- src/pi/pi_main/launch/pi_launch.py
- src/pi/pi_main/setup.py
- src/rov_msgs/msg/IPAddress.msg
- src/surface/gui/gui/operator_app.py
- src/surface/gui/gui/pilot_app.py
- src/surface/gui/gui/widgets/debug_tab.py
- src/surface/gui/gui/widgets/flood_warning.py
- src/surface/gui/gui/widgets/ip_widget.py
- src/surface/gui/gui/widgets/thruster_tester.py
- src/surface/gui/launch/operator_launch.py
Adds ip address of pi to debug tab of gui.
#71
> Add IP Address to gui debug tab

- .flake8
- .github/dependabot.yml
- .github/workflows/industrial_ci_action.yml
- .pylintrc
- Dockerfile
- mypy.ini
- pyproject.toml
- pytest.ini
- src/pi/camera_streamer/test/test_mypy.py
- src/pi/heartbeat/test/test_mypy.py
- src/pi/manipulators/test/test_mypy.py
- src/pi/pi_main/test/test_mypy.py
- src/pi/pixhawk_communication/test/test_mypy.py
- src/pi/realsense/test/test_mypy.py
- src/surface/flight_control/test/test_mypy.py
- src/surface/gui/test/test_mypy.py
- src/surface/ps5_controller/test/test_mypy.py
- src/surface/rov_flir/test/test_mypy.py
- src/surface/rov_gazebo/test/test_mypy.py
- src/surface/surface_main/test/test_mypy.py
- src/surface/vehicle_manager/test/test_mypy.py
Use to improve docker cacheing
- Closes #
#112
> Switch to pyroject.toml

- .github/workflows/industrial_ci_action.yml
> Invincible rmc patch 1

- .gitmodules
> Remove flir submod

- src/float/package.xml
- src/float/setup.py
- src/float/test/test_cpplint.py
> Adds auto testing for float code

- src/pi/manipulators/launch/manip_launch.py
- src/pi/manipulators/manipulators/lgpio_manipulator.py
- src/pi/manipulators/manipulators/lgpio_manipulator_dry_run.py
- src/pi/manipulators/setup.py
- src/pi/pi_main/README.md
- src/pi/pi_main/pi_main/copy.py
- src/pi/pi_main/test/test_run_on_boot.py
Fix #158 bug.
Add lgpio relay control.
#158 
- Closes #
> Lgpio manipulators

- src/surface/gui/gui/pilot_app.py
> bigger video

- src/float/setup.cfg
- src/float/setup.py
Removes build error for float "package".
- Closes #
> Float better build

- src/pi/pi_main/README.md
Adds documentation on fast boot.
#153 
- Closes #
#153
> Add doc on how to enable fast boot.

- src/pi/manipulators/manipulators/valve_manipulator_node.py
- src/rov_msgs/msg/ValveManip.msg
- src/surface/flight_control/flight_control/manual_control_node.py
Lets Valve manip be spun the other direction
#145
> Valve manip reverse

- src/surface/flight_control/flight_control/control_inverter_node.py
> Generalize controller squaring

- src/rov_msgs/msg/PixhawkInstruction.msg
- src/rov_msgs/srv/AutonomousFlight.srv
- src/surface/flight_control/flight_control/auto_docking_node.py
- src/surface/flight_control/flight_control/control_inverter_node.py
- src/surface/flight_control/flight_control/keyboard_control_node.py
- src/surface/flight_control/flight_control/manual_control_node.py
- src/surface/flight_control/flight_control/multiplexer.py
- src/surface/flight_control/launch/flight_control_launch.py
- src/surface/flight_control/launch/keyboard_control_launch.py
- src/surface/flight_control/setup.py
- src/surface/flight_control/test/test_manual_control.py
- src/surface/gui/gui/operator_app.py
- src/surface/gui/gui/widgets/task_selector.py
- src/surface/gui/launch/operator_launch.py
- src/surface/rov_gazebo/launch/sim_launch.py
Updates to match picture in discord.
#95
> Update auto control

- src/float/float_transceiver/float_transceiver.ino
- src/float/include/rov_common.hpp
- src/float/surface_transceiver/surface_transceiver.ino
> Fix transceivers

- src/surface/flight_control/flight_control/manual_control_node.py
- src/surface/flight_control/launch/flight_control_launch.py
- src/surface/gui/gui/pilot_app.py
- src/surface/gui/gui/widgets/arm.py
Removes video switching from the GUI and adds arm/disarm buttons to the controllers
> Remove switchable video

- pyproject.toml
> try removing pyside

- src/pi/pixhawk_communication/launch/mavros_launch.py
> remove param

- src/float/float_transceiver/float_transceiver.ino
Change float schedule and disable commands when the motor is moving
> Float comp fixes
